spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/cliente?autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=UTC
    username: gleisson
    password: gleisson
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true