spring:
  datasource:
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    show-sql: true
#spring:
#  profiles:
#    active: dev
#
#---
#spring:
#  profiles: dev
#  datasource:
#    url: jdbc:mysql://localhost:3306/cliente?autoReconnect=true&useSSL=false&useTimezone=true&serverTimezone=UTC
#    username: gleisson
#    password: gleisson
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: true